services:
  - type: web
    name: org-chatbot-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    runtime: node
    autoDeploy: true
